name: electron-microscopy-segmentation
channels:
  - conda-forge
dependencies:
  - python=3.9
  - scikit-image
  - tensorflow[and-cuda]
  - tiler=0.5.7
  - tqdm
  - pip:
    - efficientnet==1.0.*
    - image-classifiers==1.0.*
    - keras-applications>=1.0.7<=1.0.8
    - segmentation_models
